name: Dev
on:
  push:
    branches:
      - "dev"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Working Repository
        id: cwr
        uses: actions/checkout@v3
      - name: Login Docker Registry
        id: ldr
        uses: docker/login-action@v2
        with:
          username: 996chris
          password: ${{ secrets.CHRIS_DOCKER_TOKEN }}
      - name: Setup Docker Buildx
        id: sdb1
        uses: docker/setup-buildx-action@v2
      - name: Build knowledge Docker Image
        id: bdi1
        uses: docker/build-push-action@v4
        with:
          provenance: false
          platforms: |
            linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.ORGANIZATIONS_NAMESPACE }}/rfm-service:0.1.${{github.run_number}}
      - name: modify the image
        run: |
          git config user.name 996chris
          sed -i "s+wows/rfm-service.*+wows/rfm-service:0.1.${{github.run_number}}+g" k8s/kustomize/overlays/dev/rfm-deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Version: ${{ github.run_number }} [skip ci]'
          git push origin dev